from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField
from wtforms.validators import InputRequired, Length,Email
class transform(FlaskForm):
    translangto  = SelectField(u'Target Language', choices=[('af', 'afrikaans'),  ('sq', 'albanian'),  ('am', 'amharic'),  ('ar', 'arabic'),  ('hy', 'armenian'),  ('az', 'azerbaijani'),  ('eu', 'basque'),  ('be', 'belarusian'),  ('bn', 'bengali'),  ('bs', 'bosnian'),  ('bg', 'bulgarian'),  ('ca', 'catalan'),  ('ceb', 'cebuano'),  ('ny', 'chichewa'),  ('zh-cn', 'chinese (simplified)'),  ('zh-tw', 'chinese (traditional)'),  ('co', 'corsican'),  ('hr', 'croatian'),  ('cs', 'czech'),  ('da', 'danish'),  ('nl', 'dutch'),  ('en', 'english'),  ('eo', 'esperanto'),  ('et', 'estonian'),  ('tl', 'filipino'),  ('fi', 'finnish'),  ('fr', 'french'),  ('fy', 'frisian'),  ('gl', 'galician'),  ('ka', 'georgian'),  ('de', 'german'),  ('el', 'greek'),  ('gu', 'gujarati'),  ('ht', 'haitian creole'),  ('ha', 'hausa'),  ('haw', 'hawaiian'),  ('iw', 'hebrew'),  ('hi', 'hindi'),  ('hmn', 'hmong'),  ('hu', 'hungarian'),  ('is', 'icelandic'),  ('ig', 'igbo'),  ('id', 'indonesian'),  ('ga', 'irish'),  ('it', 'italian'),  ('ja', 'japanese'),  ('jw', 'javanese'),  ('kn', 'kannada'),  ('kk', 'kazakh'),  ('km', 'khmer'),  ('ko', 'korean'),  ('ku', 'kurdish (kurmanji)'),  ('ky', 'kyrgyz'),  ('lo', 'lao'),  ('la', 'latin'),  ('lv', 'latvian'),  ('lt', 'lithuanian'),  ('lb', 'luxembourgish'),  ('mk', 'macedonian'),  ('mg', 'malagasy'),  ('ms', 'malay'),  ('ml', 'malayalam'),  ('mt', 'maltese'),  ('mi', 'maori'),  ('mr', 'marathi'),  ('mn', 'mongolian'),  ('my', 'myanmar (burmese)'),  ('ne', 'nepali'),  ('no', 'norwegian'),  ('ps', 'pashto'),  ('fa', 'persian'),  ('pl', 'polish'),  ('pt', 'portuguese'),  ('pa', 'punjabi'),  ('ro', 'romanian'),  ('ru', 'russian'),  ('sm', 'samoan'),  ('gd', 'scots gaelic'),  ('sr', 'serbian'),  ('st', 'sesotho'),  ('sn', 'shona'),  ('sd', 'sindhi'),  ('si', 'sinhala'),  ('sk', 'slovak'),  ('sl', 'slovenian'),  ('so', 'somali'),  ('es', 'spanish'),  ('su', 'sundanese'),  ('sw', 'swahili'),  ('sv', 'swedish'),  ('tg', 'tajik'),  ('ta', 'tamil'),  ('te', 'telugu'),  ('th', 'thai'),  ('tr', 'turkish'),  ('uk', 'ukrainian'),  ('ur', 'urdu'),  ('uz', 'uzbek'),  ('vi', 'vietnamese'),  ('cy', 'welsh'),  ('xh', 'xhosa'),  ('yi', 'yiddish'),  ('yo', 'yoruba'),  ('zu', 'zulu'),  ('fil', 'Filipino'),  ('he', 'Hebrew')],validators=[InputRequired()])
    source = SelectField(u'Source Language', choices=[('at','Auto-detect'), ('af', 'afrikaans'),  ('sq', 'albanian'),  ('am', 'amharic'),  ('ar', 'arabic'),  ('hy', 'armenian'),  ('az', 'azerbaijani'),  ('eu', 'basque'),  ('be', 'belarusian'),  ('bn', 'bengali'),  ('bs', 'bosnian'),  ('bg', 'bulgarian'),  ('ca', 'catalan'),  ('ceb', 'cebuano'),  ('ny', 'chichewa'),  ('zh-cn', 'chinese (simplified)'),  ('zh-tw', 'chinese (traditional)'),  ('co', 'corsican'),  ('hr', 'croatian'),  ('cs', 'czech'),  ('da', 'danish'),  ('nl', 'dutch'),  ('en', 'english'),  ('eo', 'esperanto'),  ('et', 'estonian'),  ('tl', 'filipino'),  ('fi', 'finnish'),  ('fr', 'french'),  ('fy', 'frisian'),  ('gl', 'galician'),  ('ka', 'georgian'),  ('de', 'german'),  ('el', 'greek'),  ('gu', 'gujarati'),  ('ht', 'haitian creole'),  ('ha', 'hausa'),  ('haw', 'hawaiian'),  ('iw', 'hebrew'),  ('hi', 'hindi'),  ('hmn', 'hmong'),  ('hu', 'hungarian'),  ('is', 'icelandic'),  ('ig', 'igbo'),  ('id', 'indonesian'),  ('ga', 'irish'),  ('it', 'italian'),  ('ja', 'japanese'),  ('jw', 'javanese'),  ('kn', 'kannada'),  ('kk', 'kazakh'),  ('km', 'khmer'),  ('ko', 'korean'),  ('ku', 'kurdish (kurmanji)'),  ('ky', 'kyrgyz'),  ('lo', 'lao'),  ('la', 'latin'),  ('lv', 'latvian'),  ('lt', 'lithuanian'),  ('lb', 'luxembourgish'),  ('mk', 'macedonian'),  ('mg', 'malagasy'),  ('ms', 'malay'),  ('ml', 'malayalam'),  ('mt', 'maltese'),  ('mi', 'maori'),  ('mr', 'marathi'),  ('mn', 'mongolian'),  ('my', 'myanmar (burmese)'),  ('ne', 'nepali'),  ('no', 'norwegian'),  ('ps', 'pashto'),  ('fa', 'persian'),  ('pl', 'polish'),  ('pt', 'portuguese'),  ('pa', 'punjabi'),  ('ro', 'romanian'),  ('ru', 'russian'),  ('sm', 'samoan'),  ('gd', 'scots gaelic'),  ('sr', 'serbian'),  ('st', 'sesotho'),  ('sn', 'shona'),  ('sd', 'sindhi'),  ('si', 'sinhala'),  ('sk', 'slovak'),  ('sl', 'slovenian'),  ('so', 'somali'),  ('es', 'spanish'),  ('su', 'sundanese'),  ('sw', 'swahili'),  ('sv', 'swedish'),  ('tg', 'tajik'),  ('ta', 'tamil'),  ('te', 'telugu'),  ('th', 'thai'),  ('tr', 'turkish'),  ('uk', 'ukrainian'),  ('ur', 'urdu'),  ('uz', 'uzbek'),  ('vi', 'vietnamese'),  ('cy', 'welsh'),  ('xh', 'xhosa'),  ('yi', 'yiddish'),  ('yo', 'yoruba'),  ('zu', 'zulu'),  ('fil', 'Filipino'),  ('he', 'Hebrew')],validators=[InputRequired()])
    tasktotrans = StringField('What do you want to translate',validators=[InputRequired()])
    
    submit = SubmitField('Submit')
class contactform(FlaskForm):
    name = StringField('What is your name',validators=[InputRequired()])
    email = StringField('what is your email',validators=[InputRequired(),Email(message='Email required')])
    body = TextAreaField('What feedback do you want to send',validators=[InputRequired(), Length(min=5)])
    
    submit = SubmitField('Submit')

class text_to_binaryForm(FlaskForm):
    text = StringField('Enter text',validators=[InputRequired()])
    submit = SubmitField('Submit')
class binary_to_text(FlaskForm):
    binary = StringField('Enter binary',validators=[InputRequired()])
    submit = SubmitField('Submit')